name: Java CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set SSH Environment
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.github_deploy_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - name: download config file and replace
      run: |
        git clone git@github.com:TC-zerol/mogu_blog_config.git
        ls
        mv -f ./mogu_blog_config/config/mogu_admin/application.yml ./mogu_admin/src/main/resources/application.yml
        mv -f ./mogu_blog_config/config/mogu_eureka/application.yml ./mogu_eureka/src/main/resources/application.yml
        mv -f ./mogu_blog_config/config/mogu_picture/application.yml ./mogu_picture/src/main/resources/application.yml
        mv -f ./mogu_blog_config/config/mogu_sms/application.yml ./mogu_sms/src/main/resources/application.yml
        mv -f ./mogu_blog_config/config/mogu_web/application.yml ./mogu_web/src/main/resources/application.yml
    - name: build
      run: | 
        mvn clean install
    - name: scp
      run: |
        rm -f ~/.ssh/id_rsa
        rm -f ~/.ssh/known_hosts
        echo "${{ secrets.github_deploy_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.DOCKER_IP }} > ~/.ssh/known_hosts
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
        scp -P ${{ secrets.DOCKER_PORT }} ./mogu_admin/target/mogu_admin-0.0.1-SNAPSHOT.jar root@${{ secrets.DOCKER_IP }}:$/home/mogu_blog/mogu_admin/
        scp -P ${{ secrets.DOCKER_PORT }} ./mogu_eureka/target/mogu_eureka-0.0.1-SNAPSHOT.jar root@${{ secrets.DOCKER_IP }}:$/home/mogu_blog/mogu_eureka/
        scp -P ${{ secrets.DOCKER_PORT }} ./mogu_picture/target/mogu_picture-0.0.1-SNAPSHOT.jar root@${{ secrets.DOCKER_IP }}:$/home/mogu_blog/mogu_picture/
        scp -P ${{ secrets.DOCKER_PORT }} ./mogu_sms/target/mogu_sms-0.0.1-SNAPSHOT.jar root@${{ secrets.DOCKER_IP }}:$/home/mogu_blog/mogu_sms/
        scp -P ${{ secrets.DOCKER_PORT }} ./mogu_web/target/mogu_admin-0.0.1-SNAPSHOT.jar root@${{ secrets.DOCKER_IP }}:$/home/mogu_blog/mogu_web/  
    - name: start_all
      run: |
        
         
      
      
