name: Java CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set SSH Environment
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.github_deploy_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - name: download config file and replace
      run: |
        git clone git@github.com:TC-zerol/mogu_blog_config.git
        mv -f /mogu_blog_config/config/mogu_admin/application.yml mogu_admin/src/main/resources/application.yml
        mv -f /mogu_blog_config/config/mogu_eureka/application.yml mogu_eureka/src/main/resources/application.yml
        mv -f /mogu_blog_config/config/mogu_picture/application.yml mogu_picture/src/main/resources/application.yml
        mv -f /mogu_blog_config/config/mogu_sms/application.yml mogu_sms/src/main/resources/application.yml
        mv -f /mogu_blog_config/config/mogu_web/application.yml mogu_web/src/main/resources/application.yml
    - name: build
      run: | 
        mvn clean install
    - name: start
      run: |
            
          
      
      
